// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AddTodoArgs {
    pub name: String,
    pub board_id: u32,
}

impl From<AddTodoArgs> for super::Reducer {
    fn from(args: AddTodoArgs) -> Self {
        Self::AddTodo {
            name: args.name,
            board_id: args.board_id,
}
}
}

impl __sdk::InModule for AddTodoArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `add_todo`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait add_todo {
    /// Request that the remote module invoke the reducer `add_todo` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`add_todo:add_todo_then`] to run a callback after the reducer completes.
    fn add_todo(&self, name: String,
board_id: u32,
) -> __sdk::Result<()> {
        self.add_todo_then(name, board_id,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `add_todo` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn add_todo_then(
        &self,
        name: String,
board_id: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl add_todo for super::RemoteReducers {
    fn add_todo_then(
        &self,
        name: String,
board_id: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(AddTodoArgs { name, board_id,  }, callback)
    }
}

