// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AssignBoardArgs {
    pub board_id: u32,
    pub user_id: __sdk::Identity,
}

impl From<AssignBoardArgs> for super::Reducer {
    fn from(args: AssignBoardArgs) -> Self {
        Self::AssignBoard {
            board_id: args.board_id,
            user_id: args.user_id,
        }
    }
}

impl __sdk::InModule for AssignBoardArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `assign_board`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait assign_board {
    /// Request that the remote module invoke the reducer `assign_board` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`assign_board:assign_board_then`] to run a callback after the reducer completes.
    fn assign_board(&self, board_id: u32, user_id: __sdk::Identity) -> __sdk::Result<()> {
        self.assign_board_then(board_id, user_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `assign_board` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn assign_board_then(
        &self,
        board_id: u32,
        user_id: __sdk::Identity,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl assign_board for super::RemoteReducers {
    fn assign_board_then(
        &self,
        board_id: u32,
        user_id: __sdk::Identity,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(AssignBoardArgs { board_id, user_id }, callback)
    }
}
