// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Board {
    pub id: u32,
    pub name: String,
    pub owner: __sdk::Identity,
    pub participants: Vec::<__sdk::Identity>,
}


impl __sdk::InModule for Board {
    type Module = super::RemoteModule;
}


/// Column accessor struct for the table `Board`.
///
/// Provides typed access to columns for query building.
pub struct BoardCols {
    pub id: __sdk::__query_builder::Col<Board, u32>,
    pub name: __sdk::__query_builder::Col<Board, String>,
    pub owner: __sdk::__query_builder::Col<Board, __sdk::Identity>,
    pub participants: __sdk::__query_builder::Col<Board, Vec::<__sdk::Identity>>,
}

impl __sdk::__query_builder::HasCols for Board {
    type Cols = BoardCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        BoardCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            owner: __sdk::__query_builder::Col::new(table_name, "owner"),
            participants: __sdk::__query_builder::Col::new(table_name, "participants"),

        }
    }
}

/// Indexed column accessor struct for the table `Board`.
///
/// Provides typed access to indexed columns for query building.
pub struct BoardIxCols {
    pub id: __sdk::__query_builder::IxCol<Board, u32>,
}

impl __sdk::__query_builder::HasIxCols for Board {
    type IxCols = BoardIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        BoardIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),

        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Board {}

