// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};
use super::board_type::Board;

/// Table handle for the table `current_board`.
///
/// Obtain a handle from the [`CurrentBoardTableAccess::current_board`] method on [`super::RemoteTables`],
/// like `ctx.db.current_board()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.current_board().on_insert(...)`.
pub struct CurrentBoardTableHandle<'ctx> {
    imp: __sdk::TableHandle<Board>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `current_board`.
///
/// Implemented for [`super::RemoteTables`].
pub trait CurrentBoardTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`CurrentBoardTableHandle`], which mediates access to the table `current_board`.
    fn current_board(&self) -> CurrentBoardTableHandle<'_>;
}

impl CurrentBoardTableAccess for super::RemoteTables {
    fn current_board(&self) -> CurrentBoardTableHandle<'_> {
        CurrentBoardTableHandle {
            imp: self.imp.get_table::<Board>("current_board"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct CurrentBoardInsertCallbackId(__sdk::CallbackId);
pub struct CurrentBoardDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for CurrentBoardTableHandle<'ctx> {
    type Row = Board;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 { self.imp.count() }
    fn iter(&self) -> impl Iterator<Item = Board> + '_ { self.imp.iter() }

    type InsertCallbackId = CurrentBoardInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CurrentBoardInsertCallbackId {
        CurrentBoardInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: CurrentBoardInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = CurrentBoardDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CurrentBoardDeleteCallbackId {
        CurrentBoardDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: CurrentBoardDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct CurrentBoardUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for CurrentBoardTableHandle<'ctx> {
    type UpdateCallbackId = CurrentBoardUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> CurrentBoardUpdateCallbackId {
        CurrentBoardUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: CurrentBoardUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

        /// Access to the `id` unique index on the table `current_board`,
        /// which allows point queries on the field of the same name
        /// via the [`CurrentBoardIdUnique::find`] method.
        ///
        /// Users are encouraged not to explicitly reference this type,
        /// but to directly chain method calls,
        /// like `ctx.db.current_board().id().find(...)`.
        pub struct CurrentBoardIdUnique<'ctx> {
            imp: __sdk::UniqueConstraintHandle<Board, u32>,
            phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
        }

        impl<'ctx> CurrentBoardTableHandle<'ctx> {
            /// Get a handle on the `id` unique index on the table `current_board`.
            pub fn id(&self) -> CurrentBoardIdUnique<'ctx> {
                CurrentBoardIdUnique {
                    imp: self.imp.get_unique_constraint::<u32>("id"),
                    phantom: std::marker::PhantomData,
                }
            }
        }

        impl<'ctx> CurrentBoardIdUnique<'ctx> {
            /// Find the subscribed row whose `id` column value is equal to `col_val`,
            /// if such a row is present in the client cache.
            pub fn find(&self, col_val: &u32) -> Option<Board> {
                self.imp.find(col_val)
            }
        }
        
#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {

    let _table = client_cache.get_or_make_table::<Board>("current_board");
    _table.add_unique_constraint::<u32>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Board>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<Board>",
            "TableUpdate",
        ).with_cause(e).into()
    })
}

        #[allow(non_camel_case_types)]
        /// Extension trait for query builder access to the table `Board`.
        ///
        /// Implemented for [`__sdk::QueryTableAccessor`].
        pub trait current_boardQueryTableAccess {
            #[allow(non_snake_case)]
            /// Get a query builder for the table `Board`.
            fn current_board(&self) -> __sdk::__query_builder::Table<Board>;
        }

        impl current_boardQueryTableAccess for __sdk::QueryTableAccessor {
            fn current_board(&self) -> __sdk::__query_builder::Table<Board> {
                __sdk::__query_builder::Table::new("current_board")
            }
        }

