// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};
use super::board_type::Board;

/// Table handle for the table `my_boards`.
///
/// Obtain a handle from the [`MyBoardsTableAccess::my_boards`] method on [`super::RemoteTables`],
/// like `ctx.db.my_boards()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_boards().on_insert(...)`.
pub struct MyBoardsTableHandle<'ctx> {
    imp: __sdk::TableHandle<Board>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `my_boards`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MyBoardsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MyBoardsTableHandle`], which mediates access to the table `my_boards`.
    fn my_boards(&self) -> MyBoardsTableHandle<'_>;
}

impl MyBoardsTableAccess for super::RemoteTables {
    fn my_boards(&self) -> MyBoardsTableHandle<'_> {
        MyBoardsTableHandle {
            imp: self.imp.get_table::<Board>("my_boards"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MyBoardsInsertCallbackId(__sdk::CallbackId);
pub struct MyBoardsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for MyBoardsTableHandle<'ctx> {
    type Row = Board;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 { self.imp.count() }
    fn iter(&self) -> impl Iterator<Item = Board> + '_ { self.imp.iter() }

    type InsertCallbackId = MyBoardsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyBoardsInsertCallbackId {
        MyBoardsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyBoardsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MyBoardsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyBoardsDeleteCallbackId {
        MyBoardsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyBoardsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {

        let _table = client_cache.get_or_make_table::<Board>("my_boards");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Board>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<Board>",
            "TableUpdate",
        ).with_cause(e).into()
    })
}

        #[allow(non_camel_case_types)]
        /// Extension trait for query builder access to the table `Board`.
        ///
        /// Implemented for [`__sdk::QueryTableAccessor`].
        pub trait my_boardsQueryTableAccess {
            #[allow(non_snake_case)]
            /// Get a query builder for the table `Board`.
            fn my_boards(&self) -> __sdk::__query_builder::Table<Board>;
        }

        impl my_boardsQueryTableAccess for __sdk::QueryTableAccessor {
            fn my_boards(&self) -> __sdk::__query_builder::Table<Board> {
                __sdk::__query_builder::Table::new("my_boards")
            }
        }

