// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::user_type::User;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `my_user`.
///
/// Obtain a handle from the [`MyUserTableAccess::my_user`] method on [`super::RemoteTables`],
/// like `ctx.db.my_user()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_user().on_insert(...)`.
pub struct MyUserTableHandle<'ctx> {
    imp: __sdk::TableHandle<User>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `my_user`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MyUserTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MyUserTableHandle`], which mediates access to the table `my_user`.
    fn my_user(&self) -> MyUserTableHandle<'_>;
}

impl MyUserTableAccess for super::RemoteTables {
    fn my_user(&self) -> MyUserTableHandle<'_> {
        MyUserTableHandle {
            imp: self.imp.get_table::<User>("my_user"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MyUserInsertCallbackId(__sdk::CallbackId);
pub struct MyUserDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for MyUserTableHandle<'ctx> {
    type Row = User;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = User> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MyUserInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyUserInsertCallbackId {
        MyUserInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyUserInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MyUserDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyUserDeleteCallbackId {
        MyUserDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyUserDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct MyUserUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for MyUserTableHandle<'ctx> {
    type UpdateCallbackId = MyUserUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MyUserUpdateCallbackId {
        MyUserUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MyUserUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `my_user`,
/// which allows point queries on the field of the same name
/// via the [`MyUserIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_user().id().find(...)`.
pub struct MyUserIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<User, __sdk::Identity>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> MyUserTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `my_user`.
    pub fn id(&self) -> MyUserIdUnique<'ctx> {
        MyUserIdUnique {
            imp: self.imp.get_unique_constraint::<__sdk::Identity>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> MyUserIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &__sdk::Identity) -> Option<User> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<User>("my_user");
    _table.add_unique_constraint::<__sdk::Identity>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<User>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<User>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `User`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait my_userQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `User`.
    fn my_user(&self) -> __sdk::__query_builder::Table<User>;
}

impl my_userQueryTableAccess for __sdk::QueryTableAccessor {
    fn my_user(&self) -> __sdk::__query_builder::Table<User> {
        __sdk::__query_builder::Table::new("my_user")
    }
}
