// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct TodoUndoneArgs {
    pub id: u32,
}

impl From<TodoUndoneArgs> for super::Reducer {
    fn from(args: TodoUndoneArgs) -> Self {
        Self::TodoUndone {
            id: args.id,
}
}
}

impl __sdk::InModule for TodoUndoneArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `todo_undone`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait todo_undone {
    /// Request that the remote module invoke the reducer `todo_undone` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`todo_undone:todo_undone_then`] to run a callback after the reducer completes.
    fn todo_undone(&self, id: u32,
) -> __sdk::Result<()> {
        self.todo_undone_then(id,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `todo_undone` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn todo_undone_then(
        &self,
        id: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl todo_undone for super::RemoteReducers {
    fn todo_undone_then(
        &self,
        id: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(TodoUndoneArgs { id,  }, callback)
    }
}

