// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct TodoDoneArgs {
    pub id: u32,
}

impl From<TodoDoneArgs> for super::Reducer {
    fn from(args: TodoDoneArgs) -> Self {
        Self::TodoDone { id: args.id }
    }
}

impl __sdk::InModule for TodoDoneArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `todo_done`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait todo_done {
    /// Request that the remote module invoke the reducer `todo_done` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`todo_done:todo_done_then`] to run a callback after the reducer completes.
    fn todo_done(&self, id: u32) -> __sdk::Result<()> {
        self.todo_done_then(id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `todo_done` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn todo_done_then(
        &self,
        id: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl todo_done for super::RemoteReducers {
    fn todo_done_then(
        &self,
        id: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(TodoDoneArgs { id }, callback)
    }
}
