// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};
use super::todo_type::Todo;

/// Table handle for the table `todos`.
///
/// Obtain a handle from the [`TodosTableAccess::todos`] method on [`super::RemoteTables`],
/// like `ctx.db.todos()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.todos().on_insert(...)`.
pub struct TodosTableHandle<'ctx> {
    imp: __sdk::TableHandle<Todo>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `todos`.
///
/// Implemented for [`super::RemoteTables`].
pub trait TodosTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`TodosTableHandle`], which mediates access to the table `todos`.
    fn todos(&self) -> TodosTableHandle<'_>;
}

impl TodosTableAccess for super::RemoteTables {
    fn todos(&self) -> TodosTableHandle<'_> {
        TodosTableHandle {
            imp: self.imp.get_table::<Todo>("todos"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct TodosInsertCallbackId(__sdk::CallbackId);
pub struct TodosDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for TodosTableHandle<'ctx> {
    type Row = Todo;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 { self.imp.count() }
    fn iter(&self) -> impl Iterator<Item = Todo> + '_ { self.imp.iter() }

    type InsertCallbackId = TodosInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TodosInsertCallbackId {
        TodosInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: TodosInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = TodosDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TodosDeleteCallbackId {
        TodosDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: TodosDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct TodosUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for TodosTableHandle<'ctx> {
    type UpdateCallbackId = TodosUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> TodosUpdateCallbackId {
        TodosUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: TodosUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

        /// Access to the `id` unique index on the table `todos`,
        /// which allows point queries on the field of the same name
        /// via the [`TodosIdUnique::find`] method.
        ///
        /// Users are encouraged not to explicitly reference this type,
        /// but to directly chain method calls,
        /// like `ctx.db.todos().id().find(...)`.
        pub struct TodosIdUnique<'ctx> {
            imp: __sdk::UniqueConstraintHandle<Todo, u32>,
            phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
        }

        impl<'ctx> TodosTableHandle<'ctx> {
            /// Get a handle on the `id` unique index on the table `todos`.
            pub fn id(&self) -> TodosIdUnique<'ctx> {
                TodosIdUnique {
                    imp: self.imp.get_unique_constraint::<u32>("id"),
                    phantom: std::marker::PhantomData,
                }
            }
        }

        impl<'ctx> TodosIdUnique<'ctx> {
            /// Find the subscribed row whose `id` column value is equal to `col_val`,
            /// if such a row is present in the client cache.
            pub fn find(&self, col_val: &u32) -> Option<Todo> {
                self.imp.find(col_val)
            }
        }
        
#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {

    let _table = client_cache.get_or_make_table::<Todo>("todos");
    _table.add_unique_constraint::<u32>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Todo>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<Todo>",
            "TableUpdate",
        ).with_cause(e).into()
    })
}

        #[allow(non_camel_case_types)]
        /// Extension trait for query builder access to the table `Todo`.
        ///
        /// Implemented for [`__sdk::QueryTableAccessor`].
        pub trait todosQueryTableAccess {
            #[allow(non_snake_case)]
            /// Get a query builder for the table `Todo`.
            fn todos(&self) -> __sdk::__query_builder::Table<Todo>;
        }

        impl todosQueryTableAccess for __sdk::QueryTableAccessor {
            fn todos(&self) -> __sdk::__query_builder::Table<Todo> {
                __sdk::__query_builder::Table::new("todos")
            }
        }

