// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Todo {
    pub id: u32,
    pub name: String,
    pub done: bool,
}

impl __sdk::InModule for Todo {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Todo`.
///
/// Provides typed access to columns for query building.
pub struct TodoCols {
    pub id: __sdk::__query_builder::Col<Todo, u32>,
    pub name: __sdk::__query_builder::Col<Todo, String>,
    pub done: __sdk::__query_builder::Col<Todo, bool>,
}

impl __sdk::__query_builder::HasCols for Todo {
    type Cols = TodoCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        TodoCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            done: __sdk::__query_builder::Col::new(table_name, "done"),
        }
    }
}

/// Indexed column accessor struct for the table `Todo`.
///
/// Provides typed access to indexed columns for query building.
pub struct TodoIxCols {
    pub id: __sdk::__query_builder::IxCol<Todo, u32>,
}

impl __sdk::__query_builder::HasIxCols for Todo {
    type IxCols = TodoIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        TodoIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Todo {}
