// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateBoardArgs {
    pub name: String,
    pub id: u32,
}

impl From<UpdateBoardArgs> for super::Reducer {
    fn from(args: UpdateBoardArgs) -> Self {
        Self::UpdateBoard {
            name: args.name,
            id: args.id,
        }
    }
}

impl __sdk::InModule for UpdateBoardArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_board`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_board {
    /// Request that the remote module invoke the reducer `update_board` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`update_board:update_board_then`] to run a callback after the reducer completes.
    fn update_board(&self, name: String, id: u32) -> __sdk::Result<()> {
        self.update_board_then(name, id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `update_board` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn update_board_then(
        &self,
        name: String,
        id: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl update_board for super::RemoteReducers {
    fn update_board_then(
        &self,
        name: String,
        id: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(UpdateBoardArgs { name, id }, callback)
    }
}
